plugins {
    id 'java-library'
    id 'net.neoforged.gradle.userdev' version '7.1.38'
    id 'com.diffplug.spotless' version '6.25.0'
}

version = "${minecraft_version}-${mod_version}"
group = 'platinpython.rgbblocks'
base.archivesName = 'RGB Blocks'

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"

minecraft.accessTransformers.file 'src/main/resources/META-INF/accesstransformers.cfg'

runs {
    configureEach {
        systemProperty 'forge.logging.markers', 'REGISTRIES'

        systemProperty 'forge.logging.console.level', 'debug'

        modSource project.sourceSets.main
    }

    client {
        systemProperty 'neoforge.enabledGameTestNamespaces', 'rgbblocks'
    }

    server {
        systemProperty 'neoforge.enabledGameTestNamespaces', 'rgbblocks'
        argument '--nogui'
    }

    clientData {
        arguments.addAll '--mod', 'rgbblocks', '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
    }
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'

    exclude 'src/generated/**/.cache'
}

sourceSets.main.java {
    exclude 'platinpython/rgbblocks/util/compat/top/**'

    exclude 'platinpython/rgbblocks/client/model/**'
}

repositories {
    maven {
        url "https://www.cursemaven.com/"
        content {
            includeGroup "curse.maven"
        }
    }
}

dependencies {
    implementation 'net.neoforged:neoforge:26.1.2.76'

    compileOnly 'org.jspecify:jspecify:1.0.0'

//    implementation 'curse.maven:the-one-probe-245211:5836106'

    implementation 'curse.maven:framedblocks-441647:8255890'
}

jar {
    manifest {
        attributes([
                "Specification-Title"     : "rgbblocks",
                "Specification-Vendor"    : "PlatinPython",
                "Specification-Version"   : "1",
                "Implementation-Title"    : project.name,
                "Implementation-Version"  : project.jar.archiveVersion,
                "Implementation-Vendor"   : "PlatinPython",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

apply from: rootProject.file('codeformat/spotless-rules.gradle')
