modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT"
issueTrackerURL = "https://github.com/PlatinPython/RGBBlocks/issues"

[[mods]]
modId = "rgbblocks"
version = "${file.jarVersion}"
displayName = "RGB Blocks"
description = "Blocks in almost all colors you can imagine."
logoFile = "logo.png"
logoBlur = true
credits = "Thanks TobiBenzi for the logo and some textures, Thanks XFactHD for implementing the CTM Model"
authors = "PlatinPython"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/rgb-blocks-forge"

[[accessTransformers]]
file = "META-INF/accesstransformers.cfg"

[[dependencies.rgbblocks]]
modId = "neoforge"
versionRange = "[20.4,)"

[[dependencies.rgbblocks]]
modId = "minecraft"
versionRange = "[1.20.4,)"
